### PR TITLE
Pull Request for HA and Big Data Contest 2013

### PR DESCRIPTION
**Pull request by jamesbriggs**
Hi.

Here are my 2 submissions, for the HA (using apache) and Big Data categories.

Thanks, James.

### CODE REVIEW

**Comment by castrojo** [comment]
Got it, we're moving on to the judging phase, stay tuned! If you could email me (contact info in my profile) that would be useful for me to contact you, thanks!

**Comment by jamesbriggs** [comment]
Hi Jorge.

FYI: I noticed that somebody submitted an entry after the deadline (about 3 hours late.)

Thanks, James.

---

On Thu, 10/24/13, Jorge Castro notifications@github.com wrote:

 Subject: Re: [charm-championship] Pull Request for HA and Big Data Contest 2013 (#5)
 To: "juju/charm-championship" charm-championship@noreply.github.com
 Cc: "jamesbriggs" james.briggs@yahoo.com
 Date: Thursday, October 24, 2013, 11:46 AM

 Entry received and we've begun
 judging, I'll be in touch, thanks!

 —
 Reply to this email directly or view
 it on GitHub.

**Comment by castrojo** [comment]
On Thu, Oct 24, 2013 at 3:32 PM, jamesbriggs notifications@github.comwrote:

> FYI: I noticed that somebody submitted an entry after the deadline (about
> 3 hours late.)

Yeah we had a few people have some workflow problems so we're not being
_too_ picky, you can probably sneak in some fixes over the next few hours
if you'd like.

## 

Jorge Castro

**Comment by jamesbriggs** [comment]
Hi Jorge.

Since the deadline is kind of flexible, I'll do more testing on my contest entries.
(I noticed that the admin-generated Shift-D yaml file constraints lines are causing errors, so
just comment the constraints lines out for now.)

Here's the details of my testing ...

I'm doing some testing of juju-deployer, and noticed 3 bugs. It looks
like Shift-D in the juju admin tool is not very compatible with juju-deployer:

1) This command-line syntax does not work:

$ juju-deployer -c bigdata.yaml bigdata
2013-10-24 22:30:08 Deployment 'bigdata' not found. Available envExport
2013-10-24 22:30:08 Deployment stopped. run time: 0.17

but this does work:

$ juju-deployer -c bigdata.yaml envExport
2013-10-24 22:27:18 Starting deployment of envExport
2013-10-24 22:27:25 Deploying services...

What is going on with the last parameter there? I don't see any good docs on juju-deployer.

2) According to the constraints doc page (first 6 paragraphs) empty constraints should work:
https://juju.ubuntu.com/docs/charms-constraints.html

empty constraints from admin tool Shift-D generate an error:

In bigdata.yaml:

constraints: "cpu=,mem=,arch="

$ juju-deployer -c bigdata.yaml envExport

error: invalid value "cpu=,mem=,arch=" for flag --constraints: unknown constraint "cpu"

Changing it to cpu-power= gives this error:

 error: invalid value "cpu-power=,mem=,arch=" for flag --constraints: bad "cpu-power" constraint: must be a non-negative integer

3) The above constraints parameters should accept no argument.

Thanks, James Briggs.

---

On Thu, 10/24/13, Jorge Castro notifications@github.com wrote:

 Subject: Re: [charm-championship] Pull Request for HA and Big Data Contest 2013 (#5)
 To: "juju/charm-championship" charm-championship@noreply.github.com
 Cc: "jamesbriggs" james.briggs@yahoo.com
 Date: Thursday, October 24, 2013, 3:47 PM

 On Thu, Oct 24, 2013 at 3:32 PM,
 jamesbriggs notifications@github.comwrote:

> FYI: I noticed that somebody submitted an entry after
>  the deadline (about 3 hours late.)

 Yeah we had a few people have some workflow problems so
 we're not being

 _too_ picky, you can probably sneak in some fixes over the
 next few hours

 if you'd like.

 -- 

 Jorge Castro

 —
 Reply to this email directly or view
 it on GitHub.

**Comment by castrojo** [comment]
Hi James, can you send me an email to jorge@ubuntu.com? I need your contact
information to send you more information. Thanks!

On Fri, Oct 25, 2013 at 1:41 AM, jamesbriggs notifications@github.comwrote:

> Hi Jorge.
> 
> Since the deadline is kind of flexible, I'll do more testing on my contest
> entries.
> (I noticed that the admin-generated Shift-D yaml file constraints lines
> are causing errors, so
> just comment the constraints lines out for now.)
> 
> Here's the details of my testing ...
> 
> I'm doing some testing of juju-deployer, and noticed 3 bugs. It looks
> like Shift-D in the juju admin tool is not very compatible with
> juju-deployer:
> 
> 1) This command-line syntax does not work:
> 
> $ juju-deployer -c bigdata.yaml bigdata
> 2013-10-24 22:30:08 Deployment 'bigdata' not found. Available envExport
> 2013-10-24 22:30:08 Deployment stopped. run time: 0.17
> 
> but this does work:
> 
> $ juju-deployer -c bigdata.yaml envExport
> 2013-10-24 22:27:18 Starting deployment of envExport
> 2013-10-24 22:27:25 Deploying services...
> 
> What is going on with the last parameter there? I don't see any good docs
> on juju-deployer.
> 
> 2) According to the constraints doc page (first 6 paragraphs) empty
> constraints should work:
> https://juju.ubuntu.com/docs/charms-constraints.html
> 
> empty constraints from admin tool Shift-D generate an error:
> 
> In bigdata.yaml:
> 
> constraints: "cpu=,mem=,arch="
> 
> $ juju-deployer -c bigdata.yaml envExport
> 
> error: invalid value "cpu=,mem=,arch=" for flag --constraints: unknown
> constraint "cpu"
> 
> Changing it to cpu-power= gives this error:
> 
> error: invalid value "cpu-power=,mem=,arch=" for flag --constraints: bad
> "cpu-power" constraint: must be a non-negative integer
> 
> 3) The above constraints parameters should accept no argument.
> 
> Thanks, James Briggs.
> 
> ---
> 
> On Thu, 10/24/13, Jorge Castro notifications@github.com wrote:
> 
> Subject: Re: [charm-championship] Pull Request for HA and Big Data Contest
> 2013 (#5)
> To: "juju/charm-championship" charm-championship@noreply.github.com
> Cc: "jamesbriggs" james.briggs@yahoo.com
> Date: Thursday, October 24, 2013, 3:47 PM
> 
> On Thu, Oct 24, 2013 at 3:32 PM,
> jamesbriggs notifications@github.comwrote:
> 
> > FYI: I noticed that somebody submitted an entry after
> > the deadline (about 3 hours late.)
> 
> Yeah we had a few people have some workflow problems so
> we're not being
> 
> _too_ picky, you can probably sneak in some fixes over the
> next few hours
> 
> if you'd like.
> 
> ## 
> 
> Jorge Castro
> 
> —
> Reply to this email directly or view
> it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/juju/charm-championship/pull/5#issuecomment-27066094
> .

## 

Jorge Castro

**Pull request closed without merging**
